#!/usr/bin/env python3
"""Generate src/qrkit/internal/kanji_table.gleam from the WHATWG jis0208 index.

QR Kanji mode (ISO/IEC 18004 7.4.6) encodes JIS X 0208 characters by their
Shift JIS value. This keeps the characters of JIS X 0208 proper, rows 1-8 and
16-84 (Shift JIS 0x8140-0x84BE and 0x889F-0xEAA4), and leaves out the CP932
extensions the WHATWG index also lists (NEC row 13 and the IBM rows), because a
reader that decodes Kanji mode as strict Shift JIS would garble them.

usage: scripts/gen_kanji_table.py [index-jis0208.txt]
       (downloads https://encoding.spec.whatwg.org/index-jis0208.txt when no path is given)
"""

import pathlib
import sys
import urllib.request

INDEX_URL = "https://encoding.spec.whatwg.org/index-jis0208.txt"
OUT = pathlib.Path(__file__).resolve().parent.parent / "src/qrkit/internal/kanji_table.gleam"


def shift_jis(pointer: int) -> int:
    lead, trail = divmod(pointer, 188)
    lead_byte = lead + (0x81 if lead < 0x1F else 0xC1)
    trail_byte = trail + (0x40 if trail < 0x3F else 0x41)
    return lead_byte << 8 | trail_byte


def in_jis_x_0208(sjis: int) -> bool:
    return 0x8140 <= sjis <= 0x84BE or 0x889F <= sjis <= 0xEAA4


def main() -> None:
    if len(sys.argv) > 1:
        text = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
    else:
        with urllib.request.urlopen(INDEX_URL) as response:
            text = response.read().decode("utf-8")
    identifier = next(
        line.split(":", 1)[1].strip() for line in text.splitlines() if line.startswith("# Identifier:")
    )
    table: dict[int, int] = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        pointer, codepoint = line.split("\t")[:2]
        sjis = shift_jis(int(pointer))
        cp = int(codepoint, 16)
        # First pointer wins, as in the WHATWG Shift_JIS encoder.
        if in_jis_x_0208(sjis) and cp not in table:
            table[cp] = sjis
    pairs = sorted(table.items())
    assert all(cp <= 0xFFFF for cp, _ in pairs), "JIS X 0208 maps into the BMP"
    # Seven segments per line is the layout `gleam format` settles on, so the
    # generated file passes `gleam format --check` as written.
    segments = [f"0x{value:04X}:16" for cp, sjis in pairs for value in (cp, sjis)]
    body = ",\n".join("  " + ", ".join(segments[i : i + 7]) for i in range(0, len(segments), 7))
    OUT.write_text(
        "//// JIS X 0208 characters and their Shift JIS values for QR Kanji mode.\n"
        "////\n"
        "//// Generated by scripts/gen_kanji_table.py from the WHATWG jis0208 index\n"
        f"//// ({identifier}). Do not edit by hand.\n"
        "\n"
        f"pub const entry_count: Int = {len(pairs)}\n"
        "\n"
        "/// Sorted by code point; each entry is the code point then the Shift JIS\n"
        "/// value, 16 bits each.\n"
        "pub const entries: BitArray = <<\n"
        f"{body},\n"
        ">>\n",
        encoding="utf-8",
    )
    print(f"wrote {len(pairs)} entries to {OUT}")


if __name__ == "__main__":
    main()
